import type { Channel, Movie, Series } from './types';

export const channels: Channel[] = [
  {
    id: 1,
    name: 'Al Jazeera',
    category: 'News',
    logo: '📰',
    quality: 'HD',
    language: 'Arabic',
    streamUrl: 'https://d2rwmwqmm0ql1w.cloudfront.net/live/playlist.m3u8',
    isHd: true,
    tags: ['Live', 'Breaking', 'World'],
    epg: [
      { title: 'Morning Brief', start: '06:00', end: '08:00' },
      { title: 'News Hour', start: '18:00', end: '20:00' },
    ],
  },
  {
    id: 2,
    name: 'BBC News',
    category: 'News',
    logo: '🗞️',
    quality: 'HD',
    language: 'English',
    streamUrl: 'https://cdn.akamaized.net/Content/HLS/Live/channel(something)/index.m3u8',
    isHd: true,
    tags: ['Global', 'Live'],
    epg: [
      { title: 'World Report', start: '12:00', end: '14:00' },
      { title: 'Global Pulse', start: '21:00', end: '22:30' },
    ],
  },
  {
    id: 3,
    name: 'OSN Movies',
    category: 'Movies',
    logo: '🎬',
    quality: '4K',
    language: 'English',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    isHd: true,
    tags: ['Cinema', 'Premium'],
    epg: [{ title: 'Movie Night', start: '20:00', end: '22:00' }],
  },
  {
    id: 4,
    name: 'MBC Action',
    category: 'Movies',
    logo: '🎥',
    quality: 'HD',
    language: 'Arabic',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    isHd: true,
    tags: ['Action', 'Arabic'],
    epg: [{ title: 'Action Max', start: '21:00', end: '23:00' }],
  },
  {
    id: 5,
    name: 'beIN Sports',
    category: 'Sports',
    logo: '⚽',
    quality: '4K',
    language: 'Arabic / English',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    isHd: true,
    tags: ['Football', 'Live'],
    epg: [{ title: 'Championship Live', start: '19:30', end: '22:00' }],
  },
  {
    id: 6,
    name: 'Sky Sports',
    category: 'Sports',
    logo: '🏆',
    quality: 'HD',
    language: 'English',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    isHd: true,
    tags: ['Premier League', 'Live'],
    epg: [{ title: 'Match Day', start: '17:00', end: '19:30' }],
  },
  {
    id: 7,
    name: 'Cartoon Network',
    category: 'Kids',
    logo: '🧸',
    quality: 'HD',
    language: 'English',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    isHd: false,
    tags: ['Family', 'Animation'],
    epg: [{ title: 'Cartoon Time', start: '08:00', end: '10:00' }],
  },
  {
    id: 8,
    name: 'Space Toons',
    category: 'Kids',
    logo: '🚀',
    quality: 'HD',
    language: 'Arabic',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    isHd: true,
    tags: ['Kids', 'Family'],
    epg: [{ title: 'Adventure Club', start: '15:00', end: '17:00' }],
  },
  {
    id: 9,
    name: 'Nat Geo',
    category: 'Documentary',
    logo: '🌍',
    quality: 'HD',
    language: 'English',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    isHd: true,
    tags: ['Nature', 'Discovery'],
    epg: [{ title: 'Wild Planet', start: '18:00', end: '19:00' }],
  },
  {
    id: 10,
    name: 'MBC Variety',
    category: 'Entertainment',
    logo: '🎵',
    quality: 'HD',
    language: 'Arabic',
    streamUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    isHd: true,
    tags: ['Music', 'Shows'],
    epg: [{ title: 'Live Music', start: '20:00', end: '22:00' }],
  },
];

export const movies: Movie[] = [
  { id: 1, title: 'Midnight Echo', genre: 'Drama', duration: '2h 13m', poster: '🎭', rating: 8.7 },
  { id: 2, title: 'Crown of Sands', genre: 'Action', duration: '1h 58m', poster: '🏜️', rating: 8.3 },
  { id: 3, title: 'Silent Horizon', genre: 'Thriller', duration: '2h 04m', poster: '🌙', rating: 7.9 },
  { id: 4, title: 'Golden City', genre: 'Adventure', duration: '2h 22m', poster: '🌆', rating: 8.5 },
];

export const series: Series[] = [
  { id: 1, title: 'The Last Signal', season: 'Season 2', episodes: 12, poster: '📡', genre: 'Sci-Fi' },
  { id: 2, title: 'House of Mirrors', season: 'Season 1', episodes: 10, poster: '🪞', genre: 'Mystery' },
  { id: 3, title: 'Arabian Nights', season: 'Season 4', episodes: 14, poster: '🧭', genre: 'Fantasy' },
  { id: 4, title: 'City Lights', season: 'Season 3', episodes: 8, poster: '💡', genre: 'Drama' },
];

export const defaultSettings = {
  playlistUrl: 'https://example.com/playlist.m3u',
  xtreamUrl: 'https://example.com',
  username: 'demo-user',
  password: '********',
  parentalLock: false,
  autoplay: true,
  theme: 'dark' as const,
};
